// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-G8MW2wphdcXrdKN5n9jWpVEybn2MPTM',
    appId: '1:228003574199:web:44d3cafa648036f587b832',
    messagingSenderId: '228003574199',
    projectId: 'pr-messanger-3e286',
    authDomain: 'pr-messanger-3e286.firebaseapp.com',
    storageBucket: 'pr-messanger-3e286.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-_dQHQOevT6aoLY1PKmdyacM91N5eO-A',
    appId: '1:228003574199:android:2f5c7d943cece0c687b832',
    messagingSenderId: '228003574199',
    projectId: 'pr-messanger-3e286',
    storageBucket: 'pr-messanger-3e286.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkbvADbF7fzVowyZWMBwE151Ukpe6cBdc',
    appId: '1:228003574199:ios:b703c4fb7aa17f0787b832',
    messagingSenderId: '228003574199',
    projectId: 'pr-messanger-3e286',
    storageBucket: 'pr-messanger-3e286.appspot.com',
    iosClientId: '228003574199-isarlb6dtc8amoog53eos874fit43fl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkbvADbF7fzVowyZWMBwE151Ukpe6cBdc',
    appId: '1:228003574199:ios:b703c4fb7aa17f0787b832',
    messagingSenderId: '228003574199',
    projectId: 'pr-messanger-3e286',
    storageBucket: 'pr-messanger-3e286.appspot.com',
    iosClientId: '228003574199-isarlb6dtc8amoog53eos874fit43fl1.apps.googleusercontent.com',
    iosBundleId: 'com.example.messenger',
  );
}
